name: Security Monitoring Workflow

on:
  push:
    branches:
      - main

jobs:
  security-audit:
    runs-on: ubuntu-latest  # Ensure the workflow runs on an up-to-date environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Ensures Node.js 20 is used
        with:
          node-version: '20'

      - name: Set up Python
        uses: actions/setup-python@v4  # Keep using the latest version
        with:
          python-version: '3.x'  # Specify your required Python version

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit Security Linter
        run: |
          bandit -r ./  # Run Bandit to scan the repository

