name: Security Monitoring Workflow

on:
  push:
    branches:
      - main

jobs:
  security-audit:
    runs-on: ubuntu-latest

    env:  # Set the environment variable here to force the use of Node.js 20
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit Security Linter
        run: |
          bandit -r ./  # Run Bandit to scan the repository
