name: Security Monitoring Workflow

on:
  push:
    branches:
      - main

jobs:
  security-audit:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Use the latest version of checkout

      - name: Set up Python
        uses: actions/setup-python@v4  # Use the latest version of Python setup
        with:
          python-version: '3.x'  # Specify your required Python version

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit Security Linter
        run: |
          bandit -r ./  # Run Bandit to scan the repository
